# Generated by Django 2.2.6 on 2019-10-03 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('livros', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='livro',
            old_name='data',
            new_name='data_pub',
        ),
    ]
